root = "."
tmp_dir = "tmp"

[build]
include_ext = [ "go" ]
include_dir = [ "server" ]
cmd = "protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative ./api/hello.proto && go build -o ./tmp/main ./server/main.go"

[misc]
clean_on_exit = true